index artifacts with job-index
This is the advice in https://github.com/pypa/cibuildwheel
Hopefully it will prevent our CI failing with

Error: Failed to CreateArtifact: Received non-retryable error: Failed
request: (409) Conflict: an artifact with this name already exists on
the workflow run